In [2]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn import preprocessing

In [3]:
contrails1 = pd.read_csv('data/contrails1.csv')
# contrails1.head()
contrails1.set_index('Timesteps', inplace=True)
# contrails1.sort_values(by=["Percentage"], ascending=False)
filtered1 = contrails1[['TotalParticles', "Ice", "NewIce", "Temp"]]

contrails2 = pd.read_csv('data/contrails2.csv')
# contrails1.head()
contrails2.set_index('Timesteps', inplace=True)
# contrails1.sort_values(by=["Percentage"], ascending=False)
filtered2 = contrails2[['TotalParticles', "Ice", "NewIce", "Temp"]]

contrails3 = pd.read_csv('data/contrails3.csv')
# contrails1.head()
contrails3.set_index('Timesteps', inplace=True)
# contrails1.sort_values(by=["Percentage"], ascending=False)
filtered3 = contrails3[['TotalParticles', "Ice", "NewIce", "Temp"]]


In [4]:
data={}
npdata = []
for index, row in filtered1.iterrows():
    data["1_"+str(index)] = row.to_numpy().tolist()
    npdata.append(row.to_numpy().tolist())
    
for index, row in filtered2.iterrows():
    data["2_"+str(index)] = row.to_numpy().tolist()
    npdata.append(row.to_numpy().tolist())
    
for index, row in filtered3.iterrows():
    data["3_"+str(index)] = row.to_numpy().tolist()
    npdata.append(row.to_numpy().tolist())
    

In [5]:
"""StandardScaler removes the mean and scales each feature/variable
to unit variance. This operation is performed feature-wise in an 
independent way."""
scaler = preprocessing.StandardScaler().fit(npdata)

In [6]:
scaler.mean_

array([1893.42222222,  673.13333333,  371.57777778,  356.37822222])

In [7]:
scaler.scale_

array([559.89969296, 248.96002356, 122.52736454,  74.85937861])

In [8]:
npdata_scaled = scaler.transform(npdata)

In [9]:
nbrs = NearestNeighbors(n_neighbors=4, algorithm='kd_tree').fit(npdata_scaled)

In [10]:
distances, indices = nbrs.kneighbors(npdata_scaled)

In [20]:
# nbrs.kneighbors.predict_proba(npdata_scaled)

In [14]:
time = list(data.keys())

In [15]:
neighbors = {}
for indice in range(len(indices)):
    neighbors[time[indice]] = []   
#     print(indice)
    for i in range(1,len(indices[indice])):
        pass
#         print(i)
        neighbors[time[indice]].append(time[indices[indice][i]])

# print(indices[indice][1])

In [16]:
neighbors

{'1_0.06': ['3_0.06', '2_0.06', '2_0.07'],
 '1_0.07': ['2_0.07', '3_0.07', '1_0.06'],
 '1_0.08': ['2_0.08', '3_0.08', '3_0.09'],
 '1_0.09': ['3_0.09', '2_0.09', '2_0.1'],
 '1_0.1': ['1_0.15', '2_0.14', '2_0.17'],
 '1_0.11': ['1_0.2', '1_0.15', '1_0.19'],
 '1_0.12': ['1_0.17', '1_0.19', '1_0.16'],
 '1_0.13': ['1_0.18', '1_0.16', '1_0.17'],
 '1_0.14': ['1_0.17', '1_0.18', '1_0.16'],
 '1_0.15': ['1_0.11', '1_0.2', '1_0.19'],
 '1_0.16': ['1_0.18', '1_0.17', '1_0.14'],
 '1_0.17': ['1_0.16', '1_0.18', '1_0.12'],
 '1_0.18': ['1_0.16', '1_0.17', '1_0.14'],
 '1_0.19': ['1_0.12', '1_0.17', '1_0.14'],
 '1_0.2': ['1_0.11', '1_0.15', '1_0.19'],
 '2_0.06': ['3_0.06', '1_0.06', '2_0.07'],
 '2_0.07': ['1_0.07', '3_0.07', '1_0.06'],
 '2_0.08': ['1_0.08', '3_0.08', '3_0.09'],
 '2_0.09': ['1_0.09', '3_0.09', '2_0.1'],
 '2_0.1': ['2_0.18', '2_0.2', '2_0.15'],
 '2_0.11': ['2_0.15', '2_0.2', '2_0.12'],
 '2_0.12': ['2_0.17', '2_0.14', '2_0.11'],
 '2_0.13': ['2_0.16', '2_0.19', '2_0.17'],
 '2_0.14': ['2_0.17'

In [17]:
indices

array([[ 0, 30, 15, 16],
       [ 1, 16, 31,  0],
       [ 2, 17, 32, 33],
       [ 3, 33, 18, 19],
       [ 4,  9, 23, 26],
       [ 5, 14,  9, 13],
       [ 6, 11, 13, 10],
       [ 7, 12, 10, 11],
       [ 8, 11, 12, 10],
       [ 9,  5, 14, 13],
       [10, 12, 11,  8],
       [11, 10, 12,  6],
       [12, 10, 11,  8],
       [13,  6, 11,  8],
       [14,  5,  9, 13],
       [15, 30,  0, 16],
       [16,  1, 31,  0],
       [17,  2, 32, 33],
       [18,  3, 33, 19],
       [19, 27, 29, 24],
       [20, 24, 29, 21],
       [21, 26, 23, 20],
       [22, 25, 28, 26],
       [23, 26, 21, 25],
       [24, 20, 29, 27],
       [25, 22, 28, 26],
       [26, 23, 21, 25],
       [27, 29, 24, 20],
       [28, 25, 22, 26],
       [29, 27, 20, 24],
       [30, 15,  0, 16],
       [31,  1, 16, 17],
       [32,  2, 17, 33],
       [33,  3, 18, 19],
       [34, 41, 37, 39],
       [35, 42, 41, 37],
       [36, 40, 43, 39],
       [37, 41, 42, 36],
       [38, 44, 35,  9],
       [39, 41, 40, 42],


In [18]:
distances

array([[0.        , 0.07193564, 0.10286558, 2.25590792],
       [0.        , 0.08725421, 0.19529823, 2.33001641],
       [0.        , 0.28770238, 0.34210353, 1.33470023],
       [0.        , 0.19905752, 0.20664823, 0.80270484],
       [0.        , 0.14529325, 0.17333214, 0.17844402],
       [0.        , 0.02233114, 0.0646877 , 0.14400038],
       [0.        , 0.0568694 , 0.05955262, 0.08982797],
       [0.        , 0.0785881 , 0.10370421, 0.12570314],
       [0.        , 0.05893156, 0.06392655, 0.06653219],
       [0.        , 0.0646877 , 0.08273433, 0.11044386],
       [0.        , 0.03488196, 0.03698068, 0.06653219],
       [0.        , 0.03698068, 0.05055856, 0.0568694 ],
       [0.        , 0.03488196, 0.05055856, 0.06392655],
       [0.        , 0.05955262, 0.0713309 , 0.0760978 ],
       [0.        , 0.02233114, 0.08273433, 0.1525507 ],
       [0.        , 0.03817326, 0.10286558, 2.34030325],
       [0.        , 0.08725421, 0.20770814, 2.25590792],
       [0.        , 0.28770238,