In [24]:
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [85]:
folder = "contrails 1"
file = "0.07.csv"
path = "data/{}/{}".format(folder, file)
# reading the data
contrails = pd.read_csv(path)

# getting the ice particles
iceContrails = contrails[contrails.iceLabel == 1]
iceContrails

cellId  origId  iceLabel  Points:0  Points:1      Points:2
214     720     189         1    4.4788  0.111080  3.869900e-09
215    2298     220         1    4.7206  0.079584 -1.541400e-07
216      67     148         1    4.6024  0.139800  4.437900e-06
217    2619     265         1    4.6443  0.096278 -2.041100e-07
218    2459     261         1    4.4261  0.088270 -2.937900e-07
..      ...     ...       ...       ...       ...           ...
820     458     204         1    5.0687  0.105730 -3.955800e-07
821    2107     230         1    4.9072  0.065466 -5.743000e-07
828    1955     247         1    4.8453  0.057012 -2.173700e-07
842     137     121         1    5.7028  0.122850  1.607800e-06
847    2358     263         1    4.6744  0.078376  1.510000e-09

[131 rows x 6 columns]

In [86]:
# saving the particle IDs to a numpy array
particleID = iceContrails['origId'].to_numpy()
len(particleID)


131

In [87]:
# creating the threeD points array from the data frame
particlePosition = iceContrails[["Points:0","Points:1","Points:2"]].to_numpy()
len(particlePosition)

131

In [88]:
# calculate distance 
dis = distance.squareform(distance.pdist(particlePosition))
print(dis)

[[0.         0.24384265 0.12689286 ... 0.37046673 1.22405659 0.19831518]
 [0.24384265 0.         0.13265446 ... 0.12672642 0.98315247 0.04621579]
 [0.12689286 0.13265446 0.         ... 0.25662085 1.10053054 0.09464094]
 ...
 [0.37046673 0.12672642 0.25662085 ... 0.         0.86002377 0.17223017]
 [1.22405659 0.98315247 1.10053054 ... 0.86002377 0.         1.02936121]
 [0.19831518 0.04621579 0.09464094 ... 0.17223017 1.02936121 0.        ]]


In [89]:
#  closest neighbors
neighbors = np.argsort(dis, axis=1)
print(neighbors)

[[  0   5  10 ...  54  64  53]
 [  1 130   3 ...  64  53  49]
 [  2   3  13 ...  54  64  53]
 ...
 [128 121 127 ...  53  48  49]
 [129  59 104 ...  47  48  49]
 [130   3   1 ...  64  53  49]]


In [90]:
print(particleID[0], particleID[1])

189 220


In [91]:
print(particlePosition[0], particlePosition[1])

[4.4788e+00 1.1108e-01 3.8699e-09] [ 4.7206e+00  7.9584e-02 -1.5414e-07]


In [103]:
# create the contrails group that are closest (distance = 1)
contrailsGroup = {}

for i in range(len(neighbors)):
    contrailsGroup[particleID[i]] = []
    for j in range(1, len(neighbors[i])):
        id = neighbors[i][j]
#         print(id)
#         print(dis[i][id])
        if dis[i][id] == 0:
            pass
        elif dis[i][id] <= 1.1:
#             print(particleID[i], particleID[j])
            contrailsGroup[particleID[i]].append(particleID[id])
        else:
            break

In [104]:
contrailsGroup

{189: [252,
  298,
  303,
  261,
  297,
  296,
  286,
  148,
  244,
  265,
  310,
  263,
  336,
  220,
  323,
  325,
  328,
  319,
  247,
  250,
  230,
  179,
  294,
  194,
  348,
  122,
  238,
  264,
  353,
  157,
  368,
  237,
  362,
  173,
  204,
  384,
  371,
  308,
  344,
  198,
  231,
  223,
  346,
  392,
  400,
  152,
  326,
  61,
  35,
  33,
  153,
  171,
  197,
  135,
  397,
  342,
  405,
  48,
  74,
  167,
  142,
  170,
  359,
  394],
 220: [263,
  265,
  247,
  148,
  250,
  286,
  230,
  296,
  303,
  179,
  194,
  122,
  298,
  252,
  189,
  238,
  157,
  261,
  297,
  237,
  204,
  173,
  244,
  310,
  198,
  231,
  223,
  336,
  323,
  325,
  328,
  152,
  61,
  319,
  35,
  33,
  294,
  348,
  153,
  171,
  197,
  135,
  264,
  353,
  48,
  368,
  74,
  362,
  167,
  142,
  384,
  170,
  161,
  371,
  308,
  344,
  346,
  130,
  141,
  165,
  121,
  392,
  127,
  146,
  101,
  400,
  112,
  174,
  326],
 148: [265,
  303,
  286,
  263,
  296,
  298,
  252,
  189,
  220,

In [108]:
ids = contrailsGroup.keys()
print(len(ids))
for id in ids:
    print("{} has {} points".format(id, len(contrailsGroup[id])))

131
189 has 64 points
220 has 69 points
148 has 63 points
265 has 67 points
261 has 62 points
252 has 63 points
286 has 63 points
297 has 61 points
244 has 58 points
296 has 63 points
298 has 63 points
310 has 58 points
264 has 58 points
303 has 63 points
319 has 58 points
294 has 59 points
323 has 58 points
325 has 58 points
308 has 54 points
328 has 57 points
353 has 58 points
336 has 58 points
344 has 53 points
348 has 57 points
346 has 50 points
368 has 57 points
371 has 54 points
326 has 49 points
362 has 56 points
384 has 55 points
392 has 49 points
400 has 49 points
342 has 46 points
397 has 46 points
405 has 46 points
359 has 42 points
378 has 36 points
426 has 38 points
394 has 41 points
395 has 40 points
406 has 35 points
389 has 35 points
432 has 36 points
425 has 31 points
441 has 31 points
457 has 29 points
464 has 32 points
471 has 27 points
472 has 20 points
454 has 17 points
10 has 65 points
73 has 77 points
38 has 68 points
15 has 44 points
9 has 47 points
33 has 82 po

64